#Список сервисов (контейнеров), которые будут запущены.
# Каждый сервис — это отдельный контейнер.
services:
  # Сервис PostgreSQL — база данных для auth-service
  postgres-auth: # Уникальное имя сервиса
    image: postgres:17 # Образ. Если его нет локально, качает из Docker Hub
    container_name: auth_db # Имя контейнера. Позволяет обращаться к контейнеру по имени
    # Переменные окружения, которые передаются внутрь контейнера.
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: auth_db
    # Проброс портов: "порт_хост(ПК):порт_контейнера"
    ports:
      - "5432:5432"
    # Тома (volumes) — для сохранения данных вне контейнера.
    volumes:
      - auth_data:/var/lib/postgresql/data # Контейнер postgres, используй том postgres_data для своей папки /var/lib...

  # Сервис PostgreSQL — база данных для product-service
  postgres-product:
    image: postgres:17
    container_name: product_db
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: product_db
    # Проброс портов: "порт_хост(ПК):порт_контейнера"
    ports:
      - "5433:5432" # Порты у ПК для связи с контейнерами разные!
    volumes:
      - product_data:/var/lib/postgresql/data

# Объявление томов (volumes), которые используются сервисами (объявлены выше).
volumes:
  auth_data: # Создать том для auth_data на хосте
  # Так как тело пустое, используются настройки по умолчанию. Docker сам решит, где хранить данные на диске
  product_data: