server:
  port: 8081 # порт, на котором сервис будет слушать запросы

# Настройка уровней логирования
logging:
  level:
    # Уровни логирования:
    # ERROR - Только ошибки
    # WARN - Предупреждения + ERROR
    # INFO - Обычные рабочие события + WARN + ERROR
    # DEBUG - Подробная информация для отладки (шаги, запросы, состояния)
    # TRACE - Максимально детально (каждый шаг выполнения)
    org.flywaydb: DEBUG # Для Flyway
    org.springframework.boot.autoconfigure.flyway: DEBUG # Для автоконфигурации

spring:
  application:
    name: auth-service # имя сервиса (видно в логах, используется в Eureka)

  # Настройки подключения к БД
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: admin
    password: admin

  # Настройки JPA (ORM)
  jpa:
    hibernate:
      # ddl-auto - стратегия управления схемой БД.
      # validate - проверяет, соответствует ли схема БД @Entity-классам.
      ddl-auto: validate
    show-sql: true # вывод сгенерированные SQL-запросы в консоль
    properties:
      hibernate:
        format_sql: true # форматировать SQL с переносами строк и отпусками (иначе все в одну строку)

  # Настройки FLYWAY (миграции)
  flyway:
    enabled: true # включить миханизм миграции
    # Создать таблицу flyway_schema_history, если ее еще нет и пометить текущее состояние как базовое. Необходимо, если БД уже существовала до Flyway
    baseline-on-migrate: true
    locations: classpath:db/migration # где искать SQL-файлы миграций

# Настройки Actuator (эндпоинты для мониторинга)
management:
  endpoints:
    web:
      exposure:
        include: health,info # какие actuator-эндпоинты открыть наружу

# Настройки JWT (механизма аутентификации)
# secret - секретный ключ для подписи созданных токенов JWT
# expiration - время жизни токена
jwt:
  secret: ${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970} # Используется переменная окружения JWT_SECRET, а если ее нет, то значение по умолчанию.
  expiration: ${JWT_EXPIRATION:86400000} # 86400000 = 24 часа